[package]
name = "menhera_album"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.4.0"
async-std = "1.10.0"
actix-files = "0.6.2"
serde = { version = "1.0", features = ["derive"] }
